### ISSUE TITLE
Repository visibility

### ISSUE THREAD

**Issue by krastin** [hashicorp/learn-terraform-enforce-policies#1]
Hello,

It seems this repository is _Internal_ and yet the following pages on Learn are linking to it:

- https://learn.hashicorp.com/terraform/cloud-getting-started/enforce-policies
- https://learn.hashicorp.com/terraform/cloud-getting-started/cost-estimation

Non-HashiCorp users are experiencing 404s for the links.

**Comment by im2nguyen** [comment]
Just set the [repo](hashicorp/learn-terraform-enforce-policies) as public, thanks for flagging this!
