### ISSUE TITLE
Error in Regex since PR #11

### ISSUE THREAD

**Issue by yga-ftp** [hashicorp/learn-terraform-enforce-policies#13]
Hello,

I encountered this error :

`An error occurred: 1 error occurred:
	* ./allowed-terraform-version.sentinel:4:60: unknown escape sequence`

while trying to do the tutorial :

- <https://learn.hashicorp.com/tutorials/terraform/policy-quickstart>

I solve it by adding a missing `\` before `d` in the regex :

- before : `"^(0\\.1(4|5)|1\\.0)\\.\d+$"`

- after : `"^(0\\.1(4|5)|1\\.0)\\.\\d+$"`

**Comment by im2nguyen** [comment]
Thank you for reporting! Just merged your suggested changes
